// backend/src/config/recyclingCentres.js — JB recycling/donation centre database
// Static data for Johor Bahru area centres
// Used by nearby endpoint and centre assignment logic

const RECYCLING_CENTRES = [
    {
        id: 'centre_jb_green_01',
        name: 'Johor Bahru Green Recycling Hub',
        type: 'recycling',
        acceptsBins: ['green_bin'],
        acceptsWasteTypes: ['plastic'],
        address: '12 Jalan Sultan Ismail, Johor Bahru',
        coordinates: { lat: 1.4854, lng: 103.7618 },
        hours: '8:00 AM - 5:00 PM (Mon-Sat)',
        contact: '+60-7-222-1234',
    },
    {
        id: 'centre_jb_blue_01',
        name: 'Johor Bahru Paper Recycling Centre',
        type: 'recycling',
        acceptsBins: ['blue_bin'],
        acceptsWasteTypes: ['paper'],
        address: '45 Jalan Yahya Awal, Johor Bahru',
        coordinates: { lat: 1.4900, lng: 103.7700 },
        hours: '8:00 AM - 5:00 PM (Mon-Sat)',
        contact: '+60-7-222-5678',
    },
    {
        id: 'centre_jb_orange_01',
        name: 'JB Multi-Material Recycling Depot',
        type: 'recycling',
        acceptsBins: ['orange_bin'],
        acceptsWasteTypes: ['glass', 'metal', 'electronics'],
        address: '88 Jalan Tun Abdul Razak, Johor Bahru',
        coordinates: { lat: 1.4927, lng: 103.7414 },
        hours: '8:00 AM - 6:00 PM (Mon-Sat)',
        contact: '+60-7-333-9012',
    },
    {
        id: 'centre_jb_ewaste_01',
        name: 'JB E-Waste Collection Point',
        type: 'recycling',
        acceptsBins: ['orange_bin'],
        acceptsWasteTypes: ['electronics'],
        address: '23 Jalan Datin Halimah, Johor Bahru',
        coordinates: { lat: 1.4722, lng: 103.7561 },
        hours: '9:00 AM - 4:00 PM (Mon-Fri)',
        contact: '+60-7-444-3456',
    },
    {
        id: 'donation_clothes_jb_01',
        name: 'Kota Tinggi Donation Hub',
        type: 'donation',
        acceptsBins: ['donation'],
        acceptsWasteTypes: ['clothes'],
        address: '456 Jalan Besar, Kota Tinggi',
        coordinates: { lat: 1.7500, lng: 103.6300 },
        hours: '9:00 AM - 6:00 PM (Weekdays)',
        contact: '+60-7-555-7890',
    },
    {
        id: 'donation_clothes_jb_02',
        name: 'JB Community Clothes Bank',
        type: 'donation',
        acceptsBins: ['donation'],
        acceptsWasteTypes: ['clothes'],
        address: '15 Jalan Wong Ah Fook, Johor Bahru',
        coordinates: { lat: 1.4631, lng: 103.7612 },
        hours: '10:00 AM - 5:00 PM (Mon-Sat)',
        contact: '+60-7-666-1234',
    },
    {
        id: 'centre_jb_general_01',
        name: 'JB General Waste Disposal Facility',
        type: 'disposal',
        acceptsBins: ['black_bin'],
        acceptsWasteTypes: ['food_waste', 'general_waste'],
        address: '200 Jalan Skudai, Johor Bahru',
        coordinates: { lat: 1.5300, lng: 103.7200 },
        hours: '7:00 AM - 7:00 PM (Daily)',
        contact: '+60-7-777-5678',
    },
    {
        id: 'centre_jb_all_01',
        name: 'EcoGreen All-in-One Recycling Centre',
        type: 'recycling',
        acceptsBins: ['green_bin', 'blue_bin', 'orange_bin'],
        acceptsWasteTypes: ['plastic', 'glass', 'metal', 'paper', 'electronics'],
        address: '99 Jalan Tebrau, Johor Bahru',
        coordinates: { lat: 1.4980, lng: 103.7800 },
        hours: '8:00 AM - 6:00 PM (Mon-Sat)',
        contact: '+60-7-888-9012',
    },
];

module.exports = { RECYCLING_CENTRES };
